services:
  integrator_db:
    image: postgres:16.9
    container_name: integrator_db
    restart: always
    volumes:
      - integrator_postgres:/var/lib/postgresql/data
    ports:
      - '5434:5432'
    environment:
      POSTGRES_DB: integrator
      POSTGRES_USER: integrator
      POSTGRES_PASSWORD: integrator

volumes:
  integrator_postgres: null
